# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

target 'SimpleMessageDialog' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for SimpleMessageDialog
  pod 'SnapKit'
end

target 'ExampleApp' do
end